# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0ec8f13150c12e3265fcc8f9782ce0b08d53c46c43ce95adc3efc2dac8722807b150699485754a88716d9925b93f48571a855acfa889c018750add8287e9a46

test:
  secret_key_base: 94f714cf1d4ddd14d2166bc6271f0a994b6562c8231459b064c13b5f4d589b995adfc6b16b4525aa891a2b152b38db99841657dcaedd3455681037024b9584c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
